using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CordiSharp.Generators;

/// <summary>Emits compile-time plugin metadata for classes annotated with
/// <c>[Plugin]</c>: plugin name, config type, generated schema and inject list.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class CordiSharpPluginGenerator : IIncrementalGenerator
{
    private const string PluginAttribute = "CordiSharp.Registry.PluginAttribute";
    private const string InjectAttribute = "CordiSharp.Registry.InjectAttribute";
    private const string DefaultValueAttribute = "CordiSharp.Schema.DefaultValueAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var plugins = context.SyntaxProvider.ForAttributeWithMetadataName(
            PluginAttribute,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, ct) => CreateModel(ctx, ct));

        var compiled = plugins.Where(static m => m is not null).Select(static (m, _) => m!).Collect();

        context.RegisterSourceOutput(compiled, static (spc, models) =>
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("namespace CordiSharp.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class PluginRegistrations");
            builder.AppendLine("    {");
            builder.AppendLine("        public static void RegisterAll()");
            builder.AppendLine("        {");
            foreach (var model in models)
            {
                model.Write(builder);
            }
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            spc.AddSource("CordiSharp.Generated.PluginRegistrations", SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }

    private static PluginModel? CreateModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;
        if (type.TypeKind != TypeKind.Class) return null;

        string? name = null;
        foreach (var attribute in ctx.Attributes)
        {
            if (attribute.AttributeClass?.ToDisplayString() != PluginAttribute) continue;
            if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string
                {
                    Length: > 0
                } s)
            {
                name = s;
            }
            break;
        }
        name ??= type.Name;

        var configType = FindConfigType(type);
        var injects = new List<(string name, string? configExpr)>();
        foreach (var attribute in type.GetAttributes())
        {
            if (attribute.AttributeClass?.ToDisplayString() != InjectAttribute) continue;
            if (attribute.ConstructorArguments.Length == 0 || attribute.ConstructorArguments[0].Value is not string injectName) continue;
            string? configExpr = null;
            if (attribute.ConstructorArguments.Length > 1)
            {
                var config = attribute.ConstructorArguments[1].Value;
                configExpr = LiteralExpr(config, attribute.ConstructorArguments[1]);
            }
            injects.Add((injectName, configExpr));
        }

        var schemaBuilder = new SchemaBuilder();
        string? schemaExpr = null;
        if (configType is not null)
        {
            schemaExpr = schemaBuilder.Build(configType, 0);
        }
        return new PluginModel(type, name, configType, schemaExpr, injects);
    }

    private static INamedTypeSymbol? FindConfigType(INamedTypeSymbol type)
    {
        foreach (var iface in type.AllInterfaces)
        {
            if (!iface.IsGenericType) continue;
            var def = iface.OriginalDefinition.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            if (def is "global::CordiSharp.Registry.IPlugin<TConfig>" or "global::CordiSharp.Registry.IAsyncPlugin<TConfig>")
            {
                return (INamedTypeSymbol)iface.TypeArguments[0];
            }
        }
        return null;
    }

    /// <summary>Escapes a string for inclusion in generated C# source (backslash-free implementation).</summary>
    private static string EscapeStringLiteral(string value)
    {
        const char BS = (char)92;
        var sb = new StringBuilder();
        foreach (var ch in value)
        {
            if (ch == BS) { sb.Append(BS); sb.Append(BS); }
            else if (ch == '"') { sb.Append(BS); sb.Append('"'); }
            else sb.Append(ch);
        }
        return sb.ToString();
    }

    private static string Q(string value) => '"' + EscapeStringLiteral(value) + '"';

    private static string LiteralExpr(object? value, TypedConstant constant)
    {
        if (value is null) return "null!";
        if (value is string str) return Q(str);
        if (value is bool b) return b ? "true" : "false";
        if (value is int i) return i.ToString(CultureInfo.InvariantCulture);
        if (value is long l) return l.ToString(CultureInfo.InvariantCulture) + "L";
        if (value is double d) return d.ToString(CultureInfo.InvariantCulture) + "d";
        if (value is float f) return f.ToString(CultureInfo.InvariantCulture) + "f";
        if (value is char c) return "'" + c + "'";
        if (value.GetType().IsEnum)
        {
            return "(object)(" + value.GetType().FullName + ")" + Convert.ToInt64(value);
        }
        return "null!";
    }

    private sealed class PluginModel(
        INamedTypeSymbol type,
        string name,
        INamedTypeSymbol? configType,
        string? schemaExpr,
        List<(string, string?)> injects)
    {
        private readonly List<(string name, string? configExpr)> _injects = injects;

        public void Write(StringBuilder builder)
        {
            var typeRef = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.AppendLine("            global::CordiSharp.Registry.PluginMetadataRegistry.Register(");
            builder.AppendLine("                typeof(" + typeRef + "),");
            builder.AppendLine("                new global::CordiSharp.Registry.PluginMetadata(");
            builder.AppendLine("                    " + Q(name) + ",");
            if (configType is not null)
            {
                builder.AppendLine("                    typeof(" + configType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) + "),");
            }
            else
            {
                builder.AppendLine("                    null,");
            }
            builder.AppendLine("                    " + (schemaExpr ?? "null") + ",");
            builder.Append("                    new global::System.Collections.Generic.KeyValuePair<string, object?>[] { ");
            foreach (var (injectName, configExpr) in _injects)
            {
                builder.Append("new global::System.Collections.Generic.KeyValuePair<string, object?>(");
                builder.Append(Q(injectName));
                builder.Append(", ");
                builder.Append(configExpr ?? "null");
                builder.Append("), ");
            }
            builder.AppendLine("}));");
        }
    }

    /// <summary>Builds a schema expression from a config type using only public CordiSharp.Schema APIs.</summary>
    private sealed class SchemaBuilder
    {
        private readonly HashSet<string> _visited = [];

        public string Build(ITypeSymbol type, int depth)
        {
            if (depth > 8) return "global::CordiSharp.Schema.Schema.Any()";
            if (!_visited.Add(type.ToDisplayString())) return "global::CordiSharp.Schema.Schema.Any()";

            var nullable = type is INamedTypeSymbol { IsGenericType: true, OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };
            if (nullable)
            {
                var inner = Build(((INamedTypeSymbol)type).TypeArguments[0], depth + 1);
                return inner is null ? "global::CordiSharp.Schema.Schema.Any()" : inner + ".AsOptional()";
            }

            switch (type.SpecialType)
            {
                case SpecialType.System_String: return "global::CordiSharp.Schema.Schema.String()";
                case SpecialType.System_Boolean: return "global::CordiSharp.Schema.Schema.Boolean()";
                case SpecialType.System_Int32:
                case SpecialType.System_Int64:
                case SpecialType.System_Int16:
                case SpecialType.System_Byte:
                    return "global::CordiSharp.Schema.Schema.Integer()";
                case SpecialType.System_Double:
                case SpecialType.System_Single:
                case SpecialType.System_Decimal:
                    return "global::CordiSharp.Schema.Schema.Number()";
            }

            if (type.TypeKind == TypeKind.Enum)
            {
                var members = type.GetMembers().OfType<IFieldSymbol>()
                    .Where(f => f.HasConstantValue)
                    .Select(f => "global::CordiSharp.Schema.Schema.Literal(" + LiteralExpr(f.ConstantValue, default) + ")");
                return "global::CordiSharp.Schema.Schema.Union(" + string.Join(", ", members) + ")";
            }

            if (type is IArrayTypeSymbol array)
            {
                var inner = Build(array.ElementType, depth + 1) ?? "global::CordiSharp.Schema.Schema.Any()";
                return "global::CordiSharp.Schema.Schema.Array(" + inner + ")";
            }

            if (type is INamedTypeSymbol { IsGenericType: true } namedType)
            {
                var def = namedType.OriginalDefinition.ToDisplayString();
                var isList = def is "System.Collections.Generic.List<T>" or "System.Collections.Generic.IList<T>" or "System.Collections.Generic.IReadOnlyList<T>" or "System.Collections.Generic.ICollection<T>" or "System.Collections.Generic.IEnumerable<T>";
                var isDict = def is "System.Collections.Generic.Dictionary<K,V>" or "System.Collections.Generic.IDictionary<K,V>" or "System.Collections.Generic.IReadOnlyDictionary<K,V>";
                if (isList)
                {
                    var inner = Build(namedType.TypeArguments[0], depth + 1) ?? "global::CordiSharp.Schema.Schema.Any()";
                    return "global::CordiSharp.Schema.Schema.Array(" + inner + ")";
                }
                if (isDict)
                {
                    var inner = Build(namedType.TypeArguments[1], depth + 1) ?? "global::CordiSharp.Schema.Schema.Any()";
                    return "global::CordiSharp.Schema.Schema.Record(" + inner + ")";
                }
            }

            // nested config class
            if (type.TypeKind == TypeKind.Class && type is INamedTypeSymbol classType)
            {
                var props = classType.GetMembers().OfType<IPropertySymbol>()
                    .Where(p => p.DeclaredAccessibility == Accessibility.Public && p is { IsStatic: false, SetMethod: not null })
                    .ToList();
                var fields = new List<string>();
                foreach (var prop in props)
                {
                    var inner = Build(prop.Type, depth + 1) ?? "global::CordiSharp.Schema.Schema.Any()";
                    var attr = prop.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == DefaultValueAttribute);
                    if (attr is not null && attr.ConstructorArguments.Length > 0)
                    {
                        inner = inner + ".WithDefault(" + LiteralExpr(attr.ConstructorArguments[0].Value, attr.ConstructorArguments[0]) + ")";
                    }
                    fields.Add("[" + Q(prop.Name) + "] = " + inner);
                }
                if (props.Count == 0)
                {
                    return "global::CordiSharp.Schema.Schema.Any()";
                }
                return "global::CordiSharp.Schema.Schema.Object(new global::System.Collections.Generic.Dictionary<string, global::CordiSharp.Schema.Schema> { " + string.Join(", ", fields) + " })";
            }

            return "global::CordiSharp.Schema.Schema.Any()";
        }
    }
}