using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace CordiSharp.Generators;

/// <summary>Emits a service catalog for <c>[Service]</c> subclasses: a mapping from contract
/// interfaces (declared outside the plugin assembly) to the plugin's internal service type
/// and its service name. The host uses the catalog to resolve
/// <c>AssemblyPluginSet.GetService&lt;T&gt;()</c> without a name, and to know which internal
/// type backs a contract.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class CordiSharpServiceCatalogGenerator : IIncrementalGenerator
{
    private const string ServiceAttribute = "CordiSharp.Registry.ServiceAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var services = context.SyntaxProvider.ForAttributeWithMetadataName(
            ServiceAttribute,
            static (node, _) => node is ClassDeclarationSyntax,
            static (ctx, ct) => CreateModel(ctx, ct));

        var compiled = services.Where(static m => m is not null).Select(static (m, _) => m!).Collect();

        context.RegisterSourceOutput(compiled, static (spc, models) =>
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            builder.AppendLine("namespace CordiSharp.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    public static class PluginServiceCatalog");
            builder.AppendLine("    {");
            builder.AppendLine("        public static global::CordiSharp.Loading.ServiceCatalogEntry[] GetEntries()");
            builder.AppendLine("        {");
            builder.AppendLine("            return new global::CordiSharp.Loading.ServiceCatalogEntry[]");
            builder.AppendLine("            {");
            foreach (var model in models)
            {
                foreach (var iface in model.Interfaces)
                {
                    builder.Append("                new global::CordiSharp.Loading.ServiceCatalogEntry(typeof(");
                    builder.Append(iface);
                    builder.Append("), ");
                    builder.Append(Quote(model.Name));
                    builder.Append(", typeof(");
                    builder.Append(model.TypeRef);
                    builder.AppendLine(")),");
                }
            }
            builder.AppendLine("            };");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            spc.AddSource("CordiSharp.Generated.PluginServiceCatalog", SourceText.From(builder.ToString(), Encoding.UTF8));
        });
    }

    private static ServiceModel? CreateModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol type) return null;
        if (type.TypeKind != TypeKind.Class || type.IsAbstract) return null;

        string? name = null;
        foreach (var attribute in ctx.Attributes)
        {
            var display = attribute.AttributeClass?.ToDisplayString() ?? "";
            if (display != ServiceAttribute && display != "CordiSharp.Registry.ServiceAttribute" && display != "ServiceAttribute") continue;
            if (attribute.ConstructorArguments.Length > 0 && attribute.ConstructorArguments[0].Value is string s && s.Length > 0)
            {
                name = s;
            }
            break;
        }
        name ??= type.Name;

        // map only contracts declared OUTSIDE the plugin assembly (host/shared contracts);
        // skip plugin-local interfaces and CordiSharp framework noise (IPlugin, IContextFilter...)
        var interfaces = new SortedSet<string>(StringComparer.Ordinal);
        foreach (var iface in type.AllInterfaces)
        {
            if (iface.TypeKind != TypeKind.Interface) continue;
            if (SymbolEqualityComparer.Default.Equals(iface.ContainingAssembly, ctx.SemanticModel.Compilation.Assembly)) continue;
            // skip only the CordiSharp CORE assembly (IPlugin, IContextFilter...);
            // contracts in other assemblies (e.g. CordiSharp.Samples.Contracts) are kept
            if (string.Equals(iface.ContainingAssembly.Name, "CordiSharp", StringComparison.Ordinal)) continue;
            interfaces.Add(iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }
        if (interfaces.Count == 0) return null;

        return new ServiceModel(name, type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), interfaces);
    }

    private static string Quote(string value) => "\"" + value.Replace("\"", "\\\"") + "\"";

    private sealed class ServiceModel(string name, string typeRef, SortedSet<string> interfaces)
    {
        public string Name { get; } = name;
        public string TypeRef { get; } = typeRef;
        public SortedSet<string> Interfaces { get; } = interfaces;
    }
}
